In [53]:
import numpy as np

x = np.arange(1,10).reshape(3,3)
x[0,1] = 12
x[1,1] = 16
x[2,1] = 11
x = np.append(x,[[1,2,0]],axis=0)

print(x)
#print(x[0,1])
#print(x[1,1])
#print(x[2,1])
#y = np.arange(1,10).reshape(3,3)

#y = np.delete(y, [0,4,6,7,8])
#print(y.reshape(2,2))


[[ 1 12  3]
 [ 4 16  6]
 [ 7 11  9]
 [ 1  2  0]]
