In [27]:
import numpy as np# We create a rank 1 ndarray from a Python list that contains integers and strings


y = np.eye(6)
print(y)


print('The elements in y are of dtype:', y.dtype)
print('The elements in y are of type:', type(y))
print('The elements in y are of shape:', y.shape)

e = np.ones((5,4))
print(f"{e}\n")

x = np.full((4,5), 5)
print(f"{x}\n")

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
The elements in y are of dtype: float64
The elements in y are of type: <class 'numpy.ndarray'>
The elements in y are of shape: (6, 6)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]

