In [20]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

#function1
X = np.ones((4,4))
X[1:2] = 2
X[2:3] = 3
X[3:] = 4
print(X)
#function2
Y = np.ones((4,4)) * np.arange(1,5)
print(Y)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
